//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class CustomerEntities : DbContext
    {
        public CustomerEntities()
            : base("name=CustomerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<NCSM_CRC_DUTY_Officer> NCSM_CRC_DUTY_Officer { get; set; }
        public virtual DbSet<NCSM_Aviem_PA_Departments> NCSM_Aviem_PA_Departments { get; set; }
        public virtual DbSet<NCSM_CRC_CallerType_External> NCSM_CRC_CallerType_External { get; set; }
        public virtual DbSet<NCSM_Canadian_Red_Cross_QC_CityRegion> NCSM_Canadian_Red_Cross_QC_CityRegion { get; set; }
        public virtual DbSet<NCSM_CRC_DUTY_ContactList> NCSM_CRC_DUTY_ContactList { get; set; }
        public virtual DbSet<NCSM_CRC_Schedule> NCSM_CRC_Schedule { get; set; }
        public virtual DbSet<NCSM_CRC_SectorsInSchdule_View> NCSM_CRC_SectorsInSchdule_View { get; set; }
        public virtual DbSet<NCSM_CRC_SectorsInSchdule_View_MissingDays> NCSM_CRC_SectorsInSchdule_View_MissingDays { get; set; }
    
        public virtual ObjectResult<CRC_DUTY_Customers_SearchCustomers_Result> CRC_DUTY_Customers_SearchCustomers(string contactName)
        {
            var contactNameParameter = contactName != null ?
                new ObjectParameter("ContactName", contactName) :
                new ObjectParameter("ContactName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CRC_DUTY_Customers_SearchCustomers_Result>("CRC_DUTY_Customers_SearchCustomers", contactNameParameter);
        }
    
        public virtual ObjectResult<sp_NCSM_CRC_SectorsInSchdule_Result> sp_NCSM_CRC_SectorsInSchdule()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_NCSM_CRC_SectorsInSchdule_Result>("sp_NCSM_CRC_SectorsInSchdule");
        }
    }
}
