//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NCSM_Canadian_Red_Cross_QC_CityRegion
    {
        public int ID { get; set; }
        public string City { get; set; }
        public string Section { get; set; }
        public string Region { get; set; }
        public string SectorNumber { get; set; }
        public Nullable<bool> Active { get; set; }
    }
}
