//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NCSM_CRC_SectorsInSchdule_View_MissingDays
    {
        public string sectornumber { get; set; }
        public string sector { get; set; }
        public Nullable<int> deptid { get; set; }
        public string MissingDate { get; set; }
        public string Missing { get; set; }
        public long RowNumber { get; set; }
    }
}
