//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NCSM_CRC_Schedule
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> start_ET { get; set; }
        public Nullable<System.DateTime> end_ET { get; set; }
        public Nullable<System.DateTime> start_UTC { get; set; }
        public Nullable<System.DateTime> end_UTC { get; set; }
        public Nullable<int> deptID { get; set; }
        public Nullable<int> contactID { get; set; }
        public string sector { get; set; }
        public Nullable<bool> rotated { get; set; }
    }
}
