//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NCSM_CRC_CallerType_External
    {
        public int ID { get; set; }
        public string CallerType { get; set; }
        public string Lang { get; set; }
        public Nullable<bool> Active { get; set; }
    }
}
